### ISSUE TITLE
bind_with_graceful_shutdown example panics

### ISSUE THREAD

**Issue by euclio** [seanmonstar/warp#195]
I'm trying to run the doc example for `bind_with_graceful_shutdown`, but I get a panic.

```rust
extern crate futures;
extern crate warp;

use futures::sync::oneshot;
use warp::Filter;

fn main() {
    let routes = warp::any()
        .map(|| "Hello, World!");

    let (tx, rx) = oneshot::channel();

    let (addr, server) = warp::serve(routes)
        .bind_with_graceful_shutdown(([127, 0, 0, 1], 3030), rx);

    // Spawn the server into a runtime
    warp::spawn(server);

    // Later, start the shutdown...
    let _ = tx.send(());
}
```

Backtrace:

```
 $ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/warp-test`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:798
  10: tokio_executor::global::spawn
             at /home/euclio/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:165
  11: tokio::executor::spawn
             at /home/euclio/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/executor/mod.rs:133
  12: hyper::rt::spawn
             at /home/euclio/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.25/src/rt.rs:30
  13: warp_test::main
             at src/main.rs:17
  14: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  18: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by seanmonstar** [comment]
Ah, apologies, I wrote those docs just assuming that the user would know how to start a [runtime](https://tokio.rs/docs/getting-started/runtime/) previously.

It could look something like:

```rust
let (tx, rx) = oneshot::channel();

// Note, this will block here until the runtime is triggered to shutdown...
tokio::run(futures::future::lazy(move || {
    let routes = warp::any()
        .map(|| "Hello, World!");



    let (addr, server) = warp::serve(routes)
        .bind_with_graceful_shutdown(([127, 0, 0, 1], 3030), rx);

    // Spawn the server into a runtime
    warp::spawn(server);
    Ok(())
}));
```
